server:
  port: 8082
  error:
    include-stacktrace: never
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/db_course
    username: myuser
    password: mypassword
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true